import type { SqlStatement } from '@/lib/db';
import { sendPendingEmails } from '@/lib/email';
import { z } from 'zod';
import { storeImage, maxImageBytes } from '@/lib/media';
import { headers } from 'next/headers';
import { all,one,db,insert,statement,update,uid,now,runtime,auditRecord,guard,clearGuards } from '@/lib/db';
import { user,requireUser,requireAdmin,hashPassword,checkPassword,sessionFor,logout,basketId,csrf,rateLimit,digest,ownerSetupAvailable,verifyOwnerSetup } from '@/lib/auth';
import { getCart,changeCart,quote,publicQuote,placeOrder,orderDetail,changeOrder } from '@/lib/commerce';
import { adminList,areaFor,tableFor,saveRecord,adjustStock,refund,saveSettings,reports } from '@/lib/admin';
import { catalog,settings } from '@/lib/catalog';
import { ensureSeed } from '@/lib/seed';
import { accountInput,AppError,safeUrl } from '@/lib/validation';
export const dynamic='force-dynamic';
type Context={params:Promise<{path:string[]}>};
async function handler(request:Request,context:Context){try{
 const {path}=await context.params;const method=request.method;const isWrite=method!=='GET';if(isWrite)await csrf(request);await ensureSeed();let data:any={};if(isWrite&&!path.includes('upload')){if(Number(request.headers.get('content-length')||0)>1000000)throw new AppError('The request is too large.',413);const text=await request.text();if(text.length>1000000)throw new AppError('The request is too large.',413);data=text?JSON.parse(text):{};}
 let result:any;
 if(path[0]==='catalog'&&method==='GET')result=await catalog();
 else if(path[0]==='cart')result=isWrite?await changeCart(data):await getCart();
 else if(path[0]==='wishlist'&&isWrite){const owner=(await user())?.id||await basketId();const input=z.object({product_id:z.string().max(100),saved:z.boolean()}).parse(data);if(!await one("SELECT id FROM products WHERE id=? AND status='published'",[input.product_id]))throw new AppError('Product not found.');if(input.saved)await insert('wishlist',{id:uid(),owner,product_id:input.product_id},true).run();else await statement('DELETE FROM wishlist WHERE owner=? AND product_id=?',[owner,input.product_id]).run();result=await getCart();}
 else if(path[0]==='quote'&&isWrite)result=publicQuote(await quote(data));
 else if(path[0]==='orders'&&path.length===1&&method==='POST'){await rateLimit('checkout',15,300);result=await placeOrder(data);}
 else if(path[0]==='orders'&&method==='GET'){if(path[1])result=await orderDetail(path[1]);else{const u=await user();result=await all('SELECT id,number,total,status,payment_status,demo,created_at,city FROM orders WHERE owner=? OR user_id=? ORDER BY created_at DESC',[await basketId(),u?.id||'']);}}
 else if(path[0]==='auth'){
  if(path[1]==='me'&&method==='GET')result=await user();
  else if(path[1]==='logout'&&isWrite){await logout();result={ok:true};}
  else if(path[1]==='register'&&method==='POST'){await rateLimit('register',6,900);const input=accountInput.parse(data);if(await one('SELECT id FROM users WHERE email=?',[input.email]))throw new AppError('Unable to create this account. Try signing in or resetting your password.');const u={id:uid(),name:input.name,email:input.email,phone:input.phone||'',password_hash:hashPassword(input.password),role:'customer',created_at:now()};await insert('users',u).run();await sessionFor(u);const owner=await basketId();await db().batch([statement('UPDATE orders SET user_id=? WHERE owner=? AND user_id IS NULL',[u.id,owner]),statement('INSERT OR IGNORE INTO wishlist (id,owner,product_id) SELECT id||?, ?, product_id FROM wishlist WHERE owner=?',['-'+uid(),u.id,owner]),statement('DELETE FROM wishlist WHERE owner=?',[owner])]);result={ok:true};}
  else if(path[1]==='login'&&method==='POST'){await rateLimit('login',12,900);const input=z.object({email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().max(128)}).parse(data);await rateLimit('login-account:'+await digest(input.email),8,900);const u=await one('SELECT * FROM users WHERE email=?',[input.email]);const verified=checkPassword(input.password,u?.password_hash||hashPassword('invalid-user-timing-only'));if(!u||u.blocked||!verified){await auditRecord('anonymous','login failed','authentication').run();throw new AppError('Email or password is incorrect.',401);}await sessionFor(u);const owner=await basketId();await db().batch([statement('UPDATE orders SET user_id=? WHERE owner=? AND user_id IS NULL',[u.id,owner]),statement('INSERT OR IGNORE INTO wishlist (id,owner,product_id) SELECT id||?, ?, product_id FROM wishlist WHERE owner=?',['-'+uid(),u.id,owner]),statement('DELETE FROM wishlist WHERE owner=?',[owner]),auditRecord(u.id,'signed in','authentication')]);result={ok:true,role:u.role};}
  else if(path[1]==='password'&&method==='POST'){const u=await requireUser();await rateLimit('password',6,900);const input=z.object({current:z.string(),password:z.string().min(12).max(128)}).parse(data);const record=await one('SELECT password_hash FROM users WHERE id=?',[u.id]);if(!checkPassword(input.current,record!.password_hash))throw new AppError('Current password is incorrect.');await db().batch([update('users',{password_hash:hashPassword(input.password)},u.id),statement('DELETE FROM sessions WHERE user_id=?',[u.id])]);await sessionFor(u);result={ok:true};}
  else if(path[1]==='reset-request'&&method==='POST'){await rateLimit('reset-request',5,900);const input=z.object({email:z.string().email()}).parse(data);if(!runtime('EMAIL_API_KEY')||!runtime('EMAIL_FROM')||!runtime('SITE_ORIGIN'))throw new AppError('Password-reset email is not configured yet. Please contact the store.');const u=await one('SELECT id,email FROM users WHERE email=?',[input.email.toLowerCase()]);if(u){const token=crypto.randomUUID()+crypto.randomUUID();await db().batch([insert('reset_tokens',{id:await digest(token),user_id:u.id,expires:Date.now()+1800000}),insert('outbox',{id:uid(),recipient:u.email,subject:'Reset your Paw & Co. password',body:`Use this link within 30 minutes: ${runtime('SITE_ORIGIN')}/account/reset?token=${encodeURIComponent(token)}`,created_at:now()})]);}result={ok:true,message:'If that account exists, a reset message has been queued.'};}
  else if(path[1]==='reset'&&method==='POST'){await rateLimit('reset',6,900);const v=z.object({token:z.string().min(50).max(200),password:z.string().min(12).max(128)}).parse(data);const token=await digest(v.token);const r=await one('SELECT * FROM reset_tokens WHERE id=? AND expires>?',[token,Date.now()]);if(!r)throw new AppError('This reset link has expired or has already been used.');await db().batch([guard('SELECT expires>? FROM reset_tokens WHERE id=?',[Date.now(),token]),update('users',{password_hash:hashPassword(v.password)},r.user_id),statement('DELETE FROM sessions WHERE user_id=?',[r.user_id]),statement('DELETE FROM reset_tokens WHERE user_id=?',[r.user_id]),clearGuards()]);result={ok:true};}
  else throw new AppError('Not found.',404);
 }
 else if(path[0]==='account'&&path[1]==='profile'&&isWrite){const u=await requireUser();const v=z.object({name:z.string().min(2).max(100),phone:z.string().max(30)}).parse(data);await update('users',v,u.id).run();result={ok:true};}
 else if(path[0]==='addresses'){const u=await requireUser();if(method==='GET')result=await all('SELECT * FROM addresses WHERE user_id=?',[u.id]);else if(method==='DELETE'){await statement('DELETE FROM addresses WHERE id=? AND user_id=?',[path[1],u.id]).run();result={ok:true};}else{const v=z.object({label:z.string().min(2).max(100),data:z.string().max(3000)}).parse(data);JSON.parse(v.data);await insert('addresses',{id:uid(),user_id:u.id,...v}).run();result={ok:true};}}
 else if(path[0]==='reviews'){if(method==='GET')result=await all("SELECT r.rating,r.content,r.image,r.created_at,u.name FROM reviews r JOIN users u ON r.user_id=u.id WHERE r.product_id=? AND r.status='approved' ORDER BY r.created_at DESC",[path[1]||'']);else{const u=await requireUser();const v=z.object({product_id:z.string(),order_id:z.string(),rating:z.number().int().min(1).max(5),content:z.string().min(10).max(2000)}).parse(data);const verified=await one("SELECT o.id FROM orders o JOIN order_items i ON i.order_id=o.id WHERE o.id=? AND i.product_id=? AND o.user_id=? AND o.status='Delivered' AND o.demo=0",[v.order_id,v.product_id,u.id]);if(!verified)throw new AppError('Reviews are available after a verified order is delivered.');await insert('reviews',{id:uid(),...v,user_id:u.id,created_at:now()}).run();result={ok:true};}}
 else if(path[0]==='returns'&&isWrite){await rateLimit('returns',10,300);const v=z.object({order_id:z.string(),items:z.string().min(1).max(2000),reason:z.string().min(3).max(200),details:z.string().max(3000).default('')}).parse(data);const order=await orderDetail(v.order_id);if(!['Delivered','Returned'].includes(order.status))throw new AppError('Return requests are available after delivery.');await insert('returns',{id:uid(),...v,owner:(await user())?.id||await basketId(),created_at:now()}).run();result={ok:true};}
 else if(path[0]==='contact'&&isWrite){await rateLimit('contact',5,300);const v=z.object({name:z.string().min(2).max(100),email:z.string().email(),subject:z.string().min(2).max(150),message:z.string().min(10).max(5000),website:z.string().max(100).default('')}).parse(data);if(v.website)throw new AppError('Unable to send this message.');const {website,...fields}=v;await insert('messages',{id:uid(),...fields,created_at:now()}).run();result={ok:true};}
 else if(path[0]==='newsletter'&&isWrite){await rateLimit('newsletter',5,300);const v=z.object({email:z.string().email().transform(s=>s.toLowerCase()),consent:z.literal(true)}).parse(data);await insert('newsletter',{id:uid(),email:v.email,created_at:now()},true).run();result={ok:true};}
 else if(path[0]==='media'&&method==='GET'){throw new AppError('Image not found.',404);}
 else if(path[0]==='admin'){
  if(path[1]==='session'&&method==='GET'){const u=await user();const hasAdmin=await one("SELECT id FROM users WHERE role='super_admin' LIMIT 1");result={user:u,setup:!hasAdmin,owner_setup_available:!hasAdmin&&ownerSetupAvailable()};}
  else if(path[1]==='bootstrap'&&method==='POST'){await rateLimit('bootstrap',5,900);await verifyOwnerSetup(data.setup_key);const v=accountInput.parse(data);const u={id:uid(),name:v.name,email:v.email,phone:v.phone||'',password_hash:hashPassword(v.password),role:'super_admin',created_at:now()};if(await one("SELECT id FROM users WHERE role='super_admin'"))throw new AppError('The first administrator has already been created.',409);await db().batch([insert('settings',{key:'admin_initialized',value:JSON.stringify(now())}),insert('users',u),auditRecord(u.id,'first administrator created','users')]);await sessionFor(u);result={ok:true};}
  else {
   const resource=path[1]||'dashboard';const actor=await requireAdmin(resource==='dashboard'?'reports':areaFor(resource));
   if(resource==='dashboard'&&method==='GET')result={...(await reports()),low_stock:await all('SELECT v.*,p.name FROM variants v JOIN products p ON p.id=v.product_id WHERE v.stock<=v.low_stock'),sample_orders:(await one('SELECT COUNT(*) n FROM orders WHERE demo=1'))?.n||0};
   else if(resource==='reports'&&method==='GET'){const url=new URL(request.url);result=await reports(url.searchParams.get('from')||'',url.searchParams.get('to')||'');}
   else if(resource==='settings')result=isWrite?await saveSettings(data,actor):await settings();
   else if(resource==='upload'&&method==='POST'){throw new AppError('Use /api/admin/products/upload.',404);}
   else if(path[2]==='upload'&&method==='POST'){if(Number(request.headers.get('content-length')||0)>maxImageBytes+65536)throw new AppError('Images must be under 4 MB.',413);const form=await request.formData();const file=form.get('file');if(!(file instanceof File)||file.size>maxImageBytes)throw new AppError('Choose an image under 4 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71;const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const webp=String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!png&&!jpg&&!webp)throw new AppError('Use a PNG, JPEG or WebP image.');const ext=png?'png':jpg?'jpg':'webp';const type='image/'+(jpg?'jpeg':ext);const key=uid()+'.'+ext;result={url:await storeImage(key,bytes,type)};}
   else if(resource==='inventory'&&isWrite)result=await adjustStock(data,actor);
   else if(resource==='inventory'&&path[2]&&method==='GET')result=await all('SELECT * FROM inventory_log WHERE variant_id=? ORDER BY created_at DESC LIMIT 100',[path[2]]);
   else if(resource==='refunds'&&method==='POST')result=await refund(data,actor);
   else if(resource==='orders'&&path[2]){if(method==='GET')result=await orderDetail(path[2],true);else {if(data.tracking_url)safeUrl(data.tracking_url,true);result=await changeOrder(path[2],data,actor);}}
   else if(resource==='outbox'&&path[2]==='send'&&isWrite){result=await sendPendingEmails(20);if(!result.configured)throw new AppError('Configure EMAIL_API_KEY and EMAIL_FROM first.');}
   else if(path[2]==='bulk'&&isWrite){const v=z.object({ids:z.array(z.string()).min(1).max(50),action:z.enum(['published','draft','archived','delete']),category_id:z.string().optional(),brand_id:z.string().optional()}).parse(data);if(resource!=='products')throw new AppError('Bulk actions apply to products.');const ops:SqlStatement[]=[];for(const id of v.ids){if(v.action==='delete')ops.push(statement('DELETE FROM products WHERE id=?',[id]));else ops.push(update('products',{status:v.action,updated_at:now(),...(v.category_id?{category_id:v.category_id}:{}),...(v.brand_id?{brand_id:v.brand_id}:{})},id));}ops.push(auditRecord(actor.id,'bulk product action','products','',v));await db().batch(ops);result={ok:true};}
   else if(method==='DELETE'){if(!['products','categories','brands','discounts','content','banners','reviews'].includes(resource))throw new AppError('This record must be retained for history.');const old=await one(`SELECT * FROM ${tableFor(resource)} WHERE id=?`,[path[2]]);await db().batch([statement(`DELETE FROM ${tableFor(resource)} WHERE id=?`,[path[2]]),auditRecord(actor.id,resource+' deleted',path[2],old,'')]);result={ok:true};}
   else if(isWrite)result=await saveRecord(resource,path[2],data,actor);
   else result=await adminList(resource);
  }
 }
 else throw new AppError('Not found.',404);
 if(isWrite&&((path[0]==='orders'&&method==='POST')||(path[0]==='auth'&&path[1]==='reset-request')||(path[0]==='admin'&&path[1]==='orders'))){try{await sendPendingEmails();}catch(e){console.error('Email delivery deferred',e);}}
 return Response.json(result,{headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
}catch(e){if(e instanceof z.ZodError)return Response.json({error:e.issues[0]?.message||'Check the form fields.',fields:e.flatten().fieldErrors},{status:400});if(e instanceof AppError)return Response.json({error:e.message},{status:e.status});console.error('API request failed',e);const message=String(e);const constraint=/UNIQUE|FOREIGN KEY|CHECK constraint/.test(message);return Response.json({error:constraint?'This change conflicts with an existing record, available stock or order history. Refresh and try again.':'We could not complete the request. Please try again.'},{status:constraint?409:500});}}
export const GET=handler;export const POST=handler;export const PATCH=handler;export const DELETE=handler;
