import { StorePage } from '@/components/store/store-page';
import { AdminApp } from '@/components/admin/admin-app';
import { catalog } from '@/lib/catalog';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { runtime } from '@/lib/db';
export const dynamic='force-dynamic';
type Props={params:Promise<{route:string[]}>;searchParams:Promise<Record<string,string>>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {route}=await params;const origin=runtime('SITE_ORIGIN');if(route[0]==='admin'||route[0]==='account'||['checkout','cart','wishlist','search'].includes(route[0]))return {title:route[0]==='admin'?'Store management':route[0].replaceAll('-',' '),robots:{index:false,follow:false}};const data=await catalog();const record:any=route[0]==='products'?data.products.find(p=>p.slug===route[1]):data.pages.find(p=>p.slug===(route[1]||route[0]));const title=record?.seo_title||record?.name||record?.title||route[0].replaceAll('-',' ');return {title,description:record?.seo_description||record?.description||record?.summary||'Thoughtfully chosen pet essentials in Pakistan.',robots:{index:!data.settings.demo_mode,follow:true},...(origin?{alternates:{canonical:origin+'/'+route.join('/')}}:{})};}
export default async function Routed({params,searchParams}:Props){const {route}=await params;if(route[0]==='admin')return <AdminApp route={route.slice(1)}/>;const data=await catalog();const known=['products','shop','dogs','cats','birds','fish','small-pets','search','offers','brands','cart','checkout','wishlist','account','pet-care','contact'];if(!known.includes(route[0])&&!data.categories.some(c=>c.kind==='pet'&&c.slug===route[0])&&!data.pages.some(p=>p.slug===route[0]))notFound();if(route[0]==='products'&&!data.products.some(p=>p.slug===route[1]))notFound();const product=route[0]==='products'?data.products.find(p=>p.slug===route[1]):null;const origin=runtime('SITE_ORIGIN');const jsonld=product&&!product.demo&&origin?{'@context':'https://schema.org','@type':'Product',name:product.name,description:product.description,sku:product.variants[0]?.sku,image:product.image.startsWith('/')?origin+product.image:product.image,brand:{'@type':'Brand',name:product.brand},offers:{'@type':'Offer',priceCurrency:'PKR',price:product.variants[0]?.sale_price??product.variants[0]?.price,availability:product.variants.some(v=>v.stock>0)?'https://schema.org/InStock':'https://schema.org/OutOfStock',url:origin+'/products/'+product.slug}}:null;return <>{jsonld&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonld).replace(/</g,'\\u003c')}}/>}<StorePage data={data} route={route} query={await searchParams}/></>;}
