import type { SqlStatement } from '@/lib/db';
import { z } from 'zod';
import { all,one,db,insert,update,statement,guard,clearGuards,auditRecord,uid,now } from './db';
import { productList,settings } from './catalog';
import { productInput,AppError,safeUrl } from './validation';
import { hashPassword } from './auth';
import type { Row } from './types';
const str=z.string().trim().max(10000),short=z.string().trim().max(200),num=z.number().int().min(0).max(10000000),toggle=z.number().int().min(0).max(1);
const schemas:Record<string,z.ZodTypeAny>={
 categories:z.object({kind:z.enum(['pet','department']).default('department'),name:short.min(1),slug:short.regex(/^[a-z0-9-]+$/),parent_id:short.nullable().default(null),description:str.default(''),image:short.default(''),sort_order:num.default(0),active:toggle.default(1),seo_title:short.default(''),seo_description:str.default(''),attributes:str.default('[]')}),
 brands:z.object({name:short.min(1),slug:short.regex(/^[a-z0-9-]+$/),description:str.default(''),image:str.default(''),website:str.default(''),featured:toggle.default(0),active:toggle.default(1)}),
 discounts:z.object({code:short.min(2).transform(s=>s.toUpperCase()),type:z.enum(['percentage','fixed','free_shipping']),value:num,minimum:num.default(0),max_uses:num.default(0),per_customer:num.default(0),starts:short.default(''),expires:short.default(''),category_id:short.default(''),product_id:short.default(''),customer_email:short.default(''),automatic:toggle.default(0),active:toggle.default(1)}).refine(d=>d.type!=='percentage'||d.value<=100,{message:'Percentage discounts cannot exceed 100%.'}).refine(d=>!d.starts||!d.expires||d.starts<d.expires,{message:'Expiry must be after the start date.'}),
 content:z.object({type:z.enum(['page','article','faq']),title:short.min(2),slug:short.regex(/^[a-z0-9-]+$/),summary:str.default(''),body:str.default(''),image:str.default(''),author:short.default('Paw & Co.'),category:short.default(''),status:z.enum(['draft','published','archived']),publish_at:short.default(''),seo_title:short.default(''),seo_description:str.default('')}),
 banners:z.object({title:short.min(2),text:str.default(''),button:short.default('Shop now'),href:short.default('/shop'),image:str.default(''),mobile_image:str.default(''),starts:short.default(''),expires:short.default(''),active:toggle.default(1),sort_order:num.default(0)}),
 reviews:z.object({status:z.enum(['pending','approved','hidden','flagged'])}),
 customers:z.object({notes:str.default(''),blocked:toggle.default(0)}),
 messages:z.object({status:z.enum(['New','In progress','Resolved'])}),
 returns:z.object({status:z.enum(['Requested','Approved','Rejected','Received','Refunded'])})
};
export const areaFor=(resource:string)=>({variants:'inventory',banners:'marketing',messages:'customers',returns:'orders',refunds:'orders',newsletter:'marketing',audit:'users',outbox:'settings'}[resource]||resource);
export const tableFor=(resource:string)=>resource==='customers'?'users':resource;
export async function adminList(resource:string):Promise<Row[]>{if(resource==='products')return productList(true);if(resource==='inventory')return all('SELECT v.*,p.name,p.image product_image,p.pet FROM variants v JOIN products p ON v.product_id=p.id ORDER BY v.stock,p.name');if(resource==='customers')return all("SELECT u.id,u.name,u.email,u.phone,u.blocked,u.notes,u.created_at,COUNT(o.id) order_count,COALESCE(SUM(CASE WHEN o.status NOT IN ('Cancelled','Returned','Refunded') THEN o.total ELSE 0 END),0) total_spend,MAX(o.created_at) last_purchase FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.created_at DESC");if(resource==='users')return all('SELECT id,name,email,phone,role,blocked,created_at FROM users WHERE role!=?',['customer']);if(resource==='reviews')return all('SELECT r.*,p.name product,u.name customer FROM reviews r JOIN products p ON r.product_id=p.id JOIN users u ON r.user_id=u.id ORDER BY r.created_at DESC');const allowed=['orders','categories','brands','discounts','content','banners','messages','newsletter','returns','refunds','audit','outbox'];if(!allowed.includes(resource))throw new AppError('Page not found.',404);return all(`SELECT * FROM ${resource} ORDER BY ${['categories','brands','discounts','banners'].includes(resource)?'id':'created_at'} DESC LIMIT 1000`);}
export async function saveProduct(id:string|undefined,input:unknown,actor:Row){const {variants,...data}=productInput.parse(input);safeUrl(data.image,true);for(const url of JSON.parse(data.gallery))safeUrl(url,true);JSON.parse(data.attributes);if(data.video)safeUrl(data.video,true);const productId=id||uid();const old=id?await one('SELECT * FROM products WHERE id=?',[id]):null;if(id&&!old)throw new AppError('Product not found.',404);const ops:SqlStatement[]=[id?update('products',{...data,updated_at:now()},id):insert('products',{id:productId,...data,created_at:now(),updated_at:now()})];
 for(const v of variants){const {id:vid,...fields}=v;safeUrl(v.image,true);const existing=vid?await one('SELECT * FROM variants WHERE id=? AND product_id=?',[vid,productId]):null;if(vid&&!existing)throw new AppError('Variant does not belong to this product.');const variantId=vid||uid();if(existing){ops.push(guard('SELECT stock=? FROM variants WHERE id=?',[existing.stock,variantId]));ops.push(update('variants',fields,variantId));if(fields.stock!==existing.stock)ops.push(insert('inventory_log',{id:uid(),variant_id:variantId,previous:existing.stock,adjustment:fields.stock-existing.stock,quantity:fields.stock,reason:'Product editor adjustment',actor:actor.id,created_at:now()}));}else{ops.push(insert('variants',{id:variantId,product_id:productId,...fields}));ops.push(insert('inventory_log',{id:uid(),variant_id:variantId,previous:0,adjustment:fields.stock,quantity:fields.stock,reason:'Initial stock',actor:actor.id,created_at:now()}));}}
 const existingVariants=id?await all('SELECT id FROM variants WHERE product_id=?',[id]):[];if(existingVariants.some(v=>!variants.some(n=>n.id===v.id)))throw new AppError('Keep existing variants to preserve order history; set their stock to zero instead.');ops.push(auditRecord(actor.id,id?'product updated':'product created',productId,old,data),clearGuards());await db().batch(ops);return {id:productId};}
export async function saveRecord(resource:string,id:string|undefined,input:Row,actor:Row){if(resource==='products')return saveProduct(id,input,actor);if(resource==='users'){const data=z.object({name:short.min(2),email:z.string().email().transform(s=>s.toLowerCase()),role:z.enum(['super_admin','manager','order_manager','inventory_manager','content_editor']),blocked:toggle.default(0),password:z.string().min(12).max(128).optional()}).parse(input);const old=id?await one('SELECT * FROM users WHERE id=?',[id]):null;const {password,...fields}=data;const record:Row={...fields};if(!id&&!password)throw new AppError('Set a password of at least 12 characters.');if(password)record.password_hash=hashPassword(password);const ops:SqlStatement[]=[];if(old?.role==='super_admin'&&(fields.role!=='super_admin'||fields.blocked))ops.push(guard("SELECT COUNT(*)>0 FROM users WHERE role='super_admin' AND blocked=0 AND id!=?",[id]));const newId=id||uid();ops.push(id?update('users',record,id):insert('users',{id:newId,...record,created_at:now()}));if(id)ops.push(statement('DELETE FROM sessions WHERE user_id=?',[id]));ops.push(auditRecord(actor.id,'admin user saved',newId,'',fields),clearGuards());await db().batch(ops);return {id:newId};}
 if(!schemas[resource])throw new AppError('Unsupported record type.');const data=schemas[resource].parse(input);for(const k of ['image','mobile_image','href','website'])if(data[k])safeUrl(data[k],true);if(resource==='categories'){try{const attrs=JSON.parse(data.attributes);if(!Array.isArray(attrs)||!attrs.every(a=>typeof a==='string'))throw new Error();}catch{throw new AppError('Category attributes must be a JSON list of names.');}}if(data.parent_id==='')data.parent_id=null;if(resource==='categories'&&data.parent_id){if(id===data.parent_id)throw new AppError('A category cannot be its own parent.');const seen=new Set([id]);let parent=data.parent_id;while(parent){if(seen.has(parent))throw new AppError('Category hierarchy cannot contain a cycle.');seen.add(parent);const p=await one('SELECT parent_id FROM categories WHERE id=?',[parent]);if(!p)throw new AppError('Parent category not found.');parent=p.parent_id;}}
 const table=tableFor(resource);const old=id?await one(`SELECT * FROM ${table} WHERE id=?`,[id]):null;if(id&&!old)throw new AppError('Record not found.',404);if(['reviews','customers','messages','returns'].includes(resource)&&!id)throw new AppError('This type of record cannot be created here.');if(resource==='customers'&&old?.role!=='customer')throw new AppError('Use Users to manage staff.',403);const newId=id||uid();if(resource==='content'){data.updated_at=now();if(!id)data.created_at=now();}const ops=[id?update(table,data,id):insert(table,{id:newId,...data}),auditRecord(actor.id,resource+' saved',newId,old,data)];if(resource==='customers'&&data.blocked)ops.push(statement('DELETE FROM sessions WHERE user_id=?',[id]));await db().batch(ops);return {id:newId};}
export async function adjustStock(data:Row,actor:Row){const input=z.object({variant_id:short.min(1),adjustment:z.number().int().min(-1000000).max(1000000),reason:short.min(3)}).parse(data);const v=await one('SELECT * FROM variants WHERE id=?',[input.variant_id]);if(!v)throw new AppError('Variant not found.');await db().batch([statement('INSERT INTO inventory_log (id,variant_id,previous,adjustment,quantity,reason,actor,created_at) SELECT ?,id,stock,?,stock+?,?,?,? FROM variants WHERE id=?',[uid(),input.adjustment,input.adjustment,input.reason,actor.id,now(),input.variant_id]),statement('UPDATE variants SET stock=stock+? WHERE id=?',[input.adjustment,input.variant_id]),auditRecord(actor.id,'stock adjusted',input.variant_id,'',input)]);return {ok:true};}
export async function refund(data:Row,actor:Row){const v=z.object({order_id:short.min(1),amount:num.positive(),method:short.min(2),reason:short.min(3)}).parse(data);const o=await one('SELECT * FROM orders WHERE id=?',[v.order_id]);if(!o)throw new AppError('Order not found.');if(!['Paid','Partially refunded'].includes(o.payment_status))throw new AppError('Record payment receipt before recording a refund.');await db().batch([guard('SELECT total-COALESCE((SELECT SUM(amount) FROM refunds WHERE order_id=?),0)>=? FROM orders WHERE id=?',[o.id,v.amount,o.id]),insert('refunds',{id:uid(),...v,actor:actor.id,created_at:now()}),statement("UPDATE orders SET payment_status=CASE WHEN (SELECT SUM(amount) FROM refunds WHERE order_id=?)>=total THEN 'Refunded' ELSE 'Partially refunded' END,updated_at=? WHERE id=?",[o.id,now(),o.id]),auditRecord(actor.id,'refund recorded',o.id,'',v),clearGuards()]);return {ok:true};}
export async function saveSettings(input:Row,actor:Row){const schema=z.object({store_name:short.min(2),announcement:short,hero_title:short,hero_text:str,hero_image:str,contact_email:z.union([z.string().email(),z.literal('')]),phone:short,whatsapp:short,address:str,hours:short,demo_mode:z.boolean(),flat_shipping:num,free_shipping:num,city_rates:z.record(num),province_rates:z.record(num),weight_rate:num,pickup:z.boolean(),pickup_address:str,cod_enabled:z.boolean(),cod_max:num,cod_blocked_cities:z.array(short),bank_enabled:z.boolean(),bank_instructions:str,dispatch:str,returns_text:str,ga_id:short,meta_pixel_id:short,social:z.record(str),sections:z.array(z.object({key:short,title:short,enabled:z.boolean(),pet:short,limit:z.number().int().min(1).max(24)})).max(10),menu:z.array(z.object({label:short,href:short})).max(20)});const data=schema.parse(input);safeUrl(data.hero_image,true);data.menu.forEach(m=>safeUrl(m.href));Object.values(data.social).forEach(u=>safeUrl(u,true));if(data.ga_id&&!/^G-[A-Z0-9]+$/.test(data.ga_id))throw new AppError('Use a valid GA4 measurement ID.');if(data.meta_pixel_id&&!/^\d+$/.test(data.meta_pixel_id))throw new AppError('Use a numeric Meta Pixel ID.');if(data.bank_enabled&&!data.bank_instructions.trim())throw new AppError('Add bank transfer instructions before enabling bank transfer.');if(data.pickup&&!data.pickup_address.trim())throw new AppError('Add a pickup address before enabling pickup.');const old=await settings();if(!data.demo_mode&&(!data.contact_email||!data.address))throw new AppError('Add your business address and support email before accepting live orders.');await db().batch([...Object.entries(data).map(([key,value])=>statement('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',[key,JSON.stringify(value)])),auditRecord(actor.id,'settings updated','store',old,data)]);return {ok:true};}
export async function reports(from='',to=''){if((from&&!/^\d{4}-\d{2}-\d{2}$/.test(from))||(to&&!/^\d{4}-\d{2}-\d{2}$/.test(to)))throw new AppError('Use a valid report date.');const args:unknown[]=[];let where='WHERE demo=0';if(from){where+=' AND created_at>=?';args.push(new Date(from+'T00:00:00.000+05:00').toISOString());}if(to){where+=' AND created_at<=?';args.push(new Date(to+'T23:59:59.999+05:00').toISOString());}const orders=await all(`SELECT * FROM orders ${where} ORDER BY created_at DESC`,args);const refunds=await all('SELECT order_id,SUM(amount) amount FROM refunds GROUP BY order_id');const delivered=orders.filter(o=>o.status==='Delivered');const revenue=delivered.reduce((s,o)=>s+o.total-(refunds.find(r=>r.order_id===o.id)?.amount||0),0);const days:Record<string,number>={};const cities:Record<string,number>={};for(const o of delivered){const day=new Date(o.created_at).toLocaleDateString('en-CA',{timeZone:'Asia/Karachi'});const amount=o.total-(refunds.find(r=>r.order_id===o.id)?.amount||0);days[day]=(days[day]||0)+amount;cities[o.city]=(cities[o.city]||0)+amount;}return {revenue,orders:orders.length,delivered:delivered.length,average:delivered.length?Math.round(revenue/delivered.length):0,pending:orders.filter(o=>['New','Confirmed','Processing','Packed'].includes(o.status)).length,days:Object.entries(days).map(([date,total])=>({date,total})),cities:Object.entries(cities).map(([city,total])=>({city,total})),status:Object.fromEntries([...new Set(orders.map(o=>o.status))].map(s=>[s,orders.filter(o=>o.status===s).length])),recent:orders.slice(0,10)};}
