import { scryptSync, timingSafeEqual, randomBytes } from 'node:crypto';
import { cookies, headers } from 'next/headers';
import { db,one,statement,insert,uid,now,runtime } from './db';
import { AppError } from './validation';
import { can, type Row } from './types';
export async function digest(value:string){return Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))).toString('hex');}
export function hashPassword(password:string){const salt=randomBytes(16).toString('hex');const hash=scryptSync(password,salt,64,{N:32768,r:8,p:3,maxmem:64*1024*1024}).toString('hex');return `scrypt:32768:8:3:${salt}:${hash}`;}
export function checkPassword(password:string,stored:string){try{const [method,n,r,p,salt,hash]=stored.split(':');if(method!=='scrypt')return false;const actual=scryptSync(password,salt,64,{N:Number(n),r:Number(r),p:Number(p),maxmem:64*1024*1024});return timingSafeEqual(actual,Buffer.from(hash,'hex'));}catch{return false;}}
const secure=async()=>!(await headers()).get('host')?.includes('terminal.local') && !(await headers()).get('host')?.startsWith('localhost');
export async function setCookie(name:string,value:string,maxAge:number){(await cookies()).set(name,value,{httpOnly:true,secure:await secure(),sameSite:'lax',path:'/',maxAge});}
export async function user(){const token=(await cookies()).get('paw_session')?.value;if(!token)return null;return one<Row>('SELECT u.id,u.name,u.email,u.phone,u.role,u.blocked FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.id=? AND s.expires>? AND u.blocked=0',[await digest(token),Date.now()]);}
export async function requireUser(){const u=await user();if(!u)throw new AppError('Please sign in to continue.',401);return u;}
export async function requireAdmin(area:string){const u=await requireUser();if(!can(u.role,area))throw new AppError('Your role does not have permission for this action.',403);return u;}
export async function sessionFor(u:Row){const token=randomBytes(32).toString('hex');const maxAge=u.role==='customer'?604800:28800;await insert('sessions',{id:await digest(token),user_id:u.id,expires:Date.now()+maxAge*1000}).run();await setCookie('paw_session',token,maxAge);}
export async function basketId(){const jar=await cookies();let token=jar.get('paw_basket')?.value;let id=token?await digest(token):'';if(!id||!await one('SELECT id FROM baskets WHERE id=?',[id])){token=randomBytes(32).toString('hex');id=await digest(token);await insert('baskets',{id,user_id:null,created_at:now()}).run();await setCookie('paw_basket',token,2592000);}return id;}
export async function rateLimit(scope:string,maximum=30,seconds=60){const h=await headers();const ip=runtime('VERCEL')==='1'?(h.get('x-forwarded-for')?.split(',')[0]?.trim()||'shared'):'local';const key=scope+':'+await digest(ip);const period=Math.floor(Date.now()/(seconds*1000));const id=key+':'+period;await statement('INSERT INTO rate_limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1',[id,Date.now()+seconds*1000]).run();const row=await one('SELECT count FROM rate_limits WHERE id=?',[id]);if(row!.count>maximum)throw new AppError('Too many attempts. Please try again later.',429);}
export async function csrf(request:Request){const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)throw new AppError('Please refresh the page and try again.',403);if(request.headers.get('sec-fetch-site')==='cross-site')throw new AppError('Cross-site requests are not allowed.',403);}
export async function logout(){const token=(await cookies()).get('paw_session')?.value;if(token)await statement('DELETE FROM sessions WHERE id=?',[await digest(token)]).run();await setCookie('paw_session','',0);}

export function ownerSetupAvailable(){return runtime('ALLOW_OWNER_SETUP')==='true'&&runtime('OWNER_SETUP_SECRET').length>=32;}
export async function verifyOwnerSetup(value:unknown){if(!ownerSetupAvailable()||typeof value!=='string'||value.length>256)throw new AppError('Administrator setup is unavailable or the setup key is incorrect.',403);const expected=await digest(runtime('OWNER_SETUP_SECRET'));const supplied=await digest(value);if(!timingSafeEqual(Buffer.from(expected,'hex'),Buffer.from(supplied,'hex')))throw new AppError('Administrator setup is unavailable or the setup key is incorrect.',403);}
