import { all } from './db';
import { ensureSeed,defaults } from './seed';
import type { Catalog, Product, Row, Variant } from './types';
export async function settings(){const rows=await all('SELECT key,value FROM settings');return {...defaults,...Object.fromEntries(rows.map(r=>[r.key,JSON.parse(r.value)]))};}
export async function productList(admin=false,includeUnavailable=false):Promise<Product[]>{
 const [products,variants,reviews,sales]=await Promise.all([all(`SELECT p.*,b.active AS brand_active,c.active AS category_active,b.name AS brand,c.name AS category FROM products p JOIN brands b ON p.brand_id=b.id JOIN categories c ON p.category_id=c.id ${admin||includeUnavailable?'':"WHERE p.status='published' AND (p.publish_at='' OR p.publish_at<=?) AND b.active=1 AND c.active=1"} ORDER BY p.created_at,p.id`,admin||includeUnavailable?[]:[new Date().toISOString()]),all<Variant>('SELECT * FROM variants ORDER BY price'),all("SELECT product_id, AVG(rating) rating,COUNT(*) review_count FROM reviews WHERE status='approved' GROUP BY product_id"),all("SELECT i.product_id,SUM(i.quantity) sold FROM order_items i JOIN orders o ON i.order_id=o.id WHERE o.status='Delivered' AND o.demo=0 GROUP BY i.product_id")]);
 return products.map(p=>({...p,variants:variants.filter(v=>v.product_id===p.id).map(v=>{if(admin)return v;const {cost,...publicVariant}=v as Variant & {cost?:number};return publicVariant;}),rating:reviews.find(r=>r.product_id===p.id)?.rating||0,review_count:reviews.find(r=>r.product_id===p.id)?.review_count||0,sold:sales.find(r=>r.product_id===p.id)?.sold||0})) as Product[];
}
export async function catalog():Promise<Catalog>{try{await ensureSeed();const [products,categories,brands,pages,banners,config]=await Promise.all([productList(),all('SELECT * FROM categories WHERE active=1 ORDER BY sort_order'),all('SELECT * FROM brands WHERE active=1'),all("SELECT * FROM content WHERE status='published' AND (publish_at='' OR publish_at<=?) ORDER BY created_at DESC",[new Date().toISOString()]),all("SELECT * FROM banners WHERE active=1 AND (starts='' OR starts<=?) AND (expires='' OR expires>?) ORDER BY sort_order",[new Date().toISOString(),new Date().toISOString()]),settings()]);return {products:products.filter(p=>config.demo_mode||!p.demo),categories,brands,pages,banners,settings:Object.fromEntries(Object.keys(defaults).map(k=>[k,config[k]])),available:true};}catch(e){console.error('Catalog unavailable',e);return {products:[],categories:[],brands:[],pages:[],banners:[],settings:defaults,available:false};}}
