import type { SqlStatement } from '@/lib/db';
import { all,one,db,insert,statement,guard,clearGuards,uid,now,update,auditRecord } from './db';
import { basketId,user,digest } from './auth';
import { productList,settings } from './catalog';
import { price,money,type Cart,type Row } from './types';
import { AppError,cartInput,checkoutInput } from './validation';
export async function getCart():Promise<Cart>{const owner=await basketId();const u=await user();const [rows,products,wishes]=await Promise.all([all('SELECT * FROM basket_items WHERE basket_id=?',[owner]),productList(false,true),all('SELECT product_id FROM wishlist WHERE owner=?',[u?.id||owner])]);const items=rows.map(r=>{const product=products.find(p=>p.variants.some(v=>v.id===r.variant_id));if(!product)return null;const variant=product.variants.find(v=>v.id===r.variant_id)!;return {...r,product,variant};}).filter(Boolean) as Cart['items'];return {items,wishlist:wishes.map(w=>w.product_id),subtotal:items.reduce((sum,i)=>sum+price(i.variant)*i.quantity,0),user:u};}
export async function changeCart(input:unknown){const data=cartInput.parse(input);const owner=await basketId();const v=await one("SELECT v.*,p.status,p.publish_at,p.demo,c.active category_active,b.active brand_active FROM variants v JOIN products p ON v.product_id=p.id JOIN categories c ON c.id=p.category_id JOIN brands b ON b.id=p.brand_id WHERE v.id=?",[data.variant_id]);if(!v)throw new AppError('This product is no longer available.');const old=await one('SELECT * FROM basket_items WHERE basket_id=? AND variant_id=?',[owner,data.variant_id]);const quantity=data.mode==='add'?(old?.quantity||0)+data.quantity:data.quantity;if(quantity===0){await statement('DELETE FROM basket_items WHERE basket_id=? AND variant_id=?',[owner,data.variant_id]).run();return getCart();}if(v.status!=='published'||!v.category_active||!v.brand_active||(v.publish_at&&v.publish_at>now())||(!(await settings()).demo_mode&&v.demo))throw new AppError('This product is not available.');if(quantity>99||(!v.backorder&&quantity>v.stock))throw new AppError(`Only ${v.stock} available. Please reduce the quantity.`);const count=await one('SELECT COUNT(*) n FROM basket_items WHERE basket_id=?',[owner]);if(!old&&count!.n>=20)throw new AppError('Your basket can contain up to 20 different items.');await statement('INSERT INTO basket_items (id,basket_id,variant_id,quantity,unit_price) VALUES (?,?,?,?,?) ON CONFLICT(basket_id,variant_id) DO UPDATE SET quantity=excluded.quantity,unit_price=excluded.unit_price',[uid(),owner,data.variant_id,quantity,v.sale_price!==null?v.sale_price:v.price]).run();return getCart();}
export async function quote(input:Row){const cart=await getCart();const config=await settings();const rawCount=await one('SELECT COUNT(*) n FROM basket_items WHERE basket_id=?',[await basketId()]);if(rawCount?.n!==cart.items.length)throw new AppError('An item in your basket is no longer available. Remove it before checkout.');if(!cart.items.length)throw new AppError('Your basket is empty.');for(const item of cart.items){if(!(item.product as Row).brand_active||!(item.product as Row).category_active||item.product.status!=='published'||(item.product.publish_at&&item.product.publish_at>now())||(!config.demo_mode&&item.product.demo))throw new AppError(`${item.product.name} is no longer available.`);if(!item.variant.backorder&&item.quantity>item.variant.stock)throw new AppError(`Only ${item.variant.stock} of ${item.product.name} available. Please update your basket.`);}
 const city=String(input.city||'').trim();const province=String(input.province||'');const subtotal=cart.subtotal;const weight=cart.items.reduce((s,i)=>s+i.quantity*i.variant.weight,0);const cityMatch=Object.keys(config.city_rates||{}).find(k=>k.toLowerCase()===city.toLowerCase());const base=cityMatch?config.city_rates[cityMatch]:(config.province_rates?.[province]??config.flat_shipping);let shipping=config.free_shipping>0&&subtotal>=config.free_shipping?0:Math.round(base+Math.max(0,Math.ceil(weight/1000)-1)*config.weight_rate);if(input.delivery_method==='pickup'){if(!config.pickup)throw new AppError('Store pickup is not enabled.');shipping=0;}
 let coupon:Row|null=null;let discount=0;const code=String(input.coupon||'').trim().toUpperCase();let candidates=code?await all('SELECT * FROM discounts WHERE code=?',[code]):await all('SELECT * FROM discounts WHERE automatic=1 AND active=1');if(code&&!candidates.length)throw new AppError('That discount code was not found.');const time=now();const owner=await basketId();const email=String(input.email||'').toLowerCase();
 for(const c of candidates){const used=await one("SELECT COUNT(*) n FROM orders WHERE coupon=? AND (email=? OR owner=?)",[c.code,email,owner]);const eligible=cart.items.filter(i=>(!c.category_id||c.category_id===i.product.category_id)&&(!c.product_id||c.product_id===i.product.id));const amount=eligible.reduce((s,i)=>s+price(i.variant)*i.quantity,0);let reason='';if(!c.active||(c.starts&&time<c.starts)||(c.expires&&time>=c.expires))reason='This code is not currently active.';else if(c.max_uses>0&&c.uses>=c.max_uses)reason='This code has reached its use limit.';else if(c.per_customer>0&&used!.n>=c.per_customer)reason='You have already used this code.';else if(c.customer_email&&c.customer_email.toLowerCase()!==email)reason='This code is not available for this email address.';else if(subtotal<c.minimum)reason=`Spend ${money(c.minimum)} to use this code.`;else if(!amount)reason='This code does not apply to your items.';if(reason){if(code)throw new AppError(reason);continue;}const value=c.type==='percentage'?Math.round(amount*c.value/100):c.type==='fixed'?Math.min(amount,c.value):0;const saving=value+(c.type==='free_shipping'?shipping:0);if(!coupon||saving>discount+(coupon.type==='free_shipping'?shipping:0)){coupon=c;discount=value;}}
 if(coupon?.type==='free_shipping')shipping=0;
 const total=subtotal-discount+shipping;
 const methods=[];if(config.cod_enabled&&(!config.cod_max||total<=config.cod_max)&&!config.cod_blocked_cities.some((c:string)=>c.toLowerCase()===city.toLowerCase())&&!cart.items.some(i=>i.product.cod_disabled))methods.push('cod');if(config.bank_enabled&&config.bank_instructions.trim())methods.push('bank');
 const snapshot={items:cart.items.map(i=>[i.variant_id,i.quantity,price(i.variant)]),subtotal,discount,shipping,total,city,province,delivery_method:input.delivery_method||'delivery',coupon:(coupon as Row|null)?.code||'',methods};return {...snapshot,quote_token:await digest(JSON.stringify(snapshot)),cart,config,couponRecord:coupon};
}
export function publicQuote(q:Awaited<ReturnType<typeof quote>>){const {cart,config,couponRecord,...safe}=q;return {...safe,demo:config.demo_mode,price_changed:cart.items.some(i=>i.unit_price!==price(i.variant)),bank_instructions:config.bank_enabled?config.bank_instructions:'',dispatch:config.dispatch};}
export async function placeOrder(input:unknown){const data=checkoutInput.parse(input);const owner=await basketId();const u=await user();const key=await digest(owner+':'+data.request_key);const existing=await one('SELECT id,number FROM orders WHERE request_key=? AND owner=?',[key,owner]);if(existing)return existing;
 const q=await quote(data);if(data.quote_token!==q.quote_token)throw new AppError('Your basket or delivery cost changed. Review the updated total and submit again.',409);if(!q.methods.includes(data.payment_method))throw new AppError('This payment method is not available for the order.');
 const blocked=await one('SELECT id FROM users WHERE blocked=1 AND (email=? OR phone=?)',[data.email,data.phone]);if(blocked)throw new AppError('We cannot accept this order. Please contact the store.',403);
 const id=uid();const date=now();const number='PAW-'+date.slice(0,4)+'-'+id.slice(0,8).toUpperCase();const order={id,number,request_key:key,owner,user_id:u?.id||null,name:data.name,email:data.email,phone:data.phone,address:JSON.stringify({street:data.address,postal_code:data.postal_code||'',method:data.delivery_method}),city:data.city,province:data.province,notes:data.notes,subtotal:q.subtotal,discount:q.discount,shipping:q.shipping,total:q.total,payment_method:data.payment_method,payment_status:'Unpaid',status:'New',coupon:q.coupon,created_at:date,updated_at:date,demo:q.config.demo_mode?1:0};const ops:SqlStatement[]=[];
 for(const key of ['demo_mode','flat_shipping','free_shipping','city_rates','province_rates','weight_rate','pickup','cod_enabled','cod_max','cod_blocked_cities','bank_enabled','bank_instructions'])ops.push(guard('SELECT value=? FROM settings WHERE key=?',[JSON.stringify(q.config[key]),key]));
 if(q.couponRecord){const c=q.couponRecord;ops.push(guard("SELECT active=1 AND (max_uses=0 OR uses<max_uses) AND (starts='' OR starts<=?) AND (expires='' OR expires>?) AND value=? AND type=? AND minimum=? AND category_id=? AND product_id=? AND customer_email=? AND (per_customer=0 OR (SELECT COUNT(*) FROM orders WHERE coupon=? AND (email=? OR owner=?))<per_customer) FROM discounts WHERE id=?",[date,date,c.value,c.type,c.minimum,c.category_id,c.product_id,c.customer_email,c.code,data.email,owner,c.id]));ops.push(statement('UPDATE discounts SET uses=uses+1 WHERE id=?',[c.id]));}
 ops.push(guard('SELECT COUNT(*)=? FROM basket_items WHERE basket_id=?',[q.cart.items.length,owner]));for(const item of q.cart.items)ops.push(guard('SELECT quantity=? FROM basket_items WHERE basket_id=? AND variant_id=?',[item.quantity,owner,item.variant_id]));
 ops.push(insert('orders',order));for(const i of q.cart.items){ops.push(guard("SELECT COALESCE(v.sale_price,v.price)=? AND p.status='published' AND (p.publish_at='' OR p.publish_at<=?) AND b.active=1 AND c.active=1 AND p.demo=? AND p.cod_disabled=? AND v.weight=? FROM variants v JOIN products p ON v.product_id=p.id JOIN brands b ON b.id=p.brand_id JOIN categories c ON c.id=p.category_id WHERE v.id=?",[price(i.variant),date,i.product.demo,i.product.cod_disabled,i.variant.weight,i.variant_id]));ops.push(statement('INSERT INTO inventory_log (id,variant_id,previous,adjustment,quantity,reason,actor,created_at) SELECT ?,id,stock,?,stock-?,?,?,? FROM variants WHERE id=?',[uid(),-i.quantity,i.quantity,'Sale '+number,u?.id||'guest',date,i.variant_id]));ops.push(statement('UPDATE variants SET stock=stock-? WHERE id=?',[i.quantity,i.variant_id]));ops.push(insert('order_items',{id:uid(),order_id:id,variant_id:i.variant_id,product_id:i.product.id,name:i.product.name,label:i.variant.label,sku:i.variant.sku,image:i.variant.image||i.product.image,quantity:i.quantity,price:price(i.variant)}));}
 ops.push(insert('order_history',{id:uid(),order_id:id,status:'New',actor:u?.id||'guest',created_at:date}));ops.push(insert('outbox',{id:uid(),recipient:data.email,subject:`${q.config.demo_mode?'Sample ':''}order received · ${number}`,body:`Hello ${data.name},\n\nWe have received ${q.config.demo_mode?'your sample order (not a purchase)':'your order'} ${number}.\nTotal: ${money(q.total)}\nPayment: ${data.payment_method==='cod'?'Cash on Delivery':'Bank transfer'}\n\n${q.config.dispatch}\n\n${q.config.store_name}`,status:q.config.demo_mode?'sample':'pending',created_at:date}));ops.push(statement('DELETE FROM basket_items WHERE basket_id=?',[owner]));ops.push(clearGuards());
 try{await db().batch(ops);}catch(error){const retry=await one('SELECT id,number FROM orders WHERE request_key=? AND owner=?',[key,owner]);if(retry)return retry;console.error('Order transaction rejected',error);throw new AppError('An item, price or discount changed during checkout. Refresh your basket and try again.',409);}return {id,number};}
export async function orderDetail(id:string,admin=false):Promise<Row>{const u=await user();const owner=await basketId();const order=await one(`SELECT * FROM orders WHERE (id=? OR number=?) ${admin?'':'AND (owner=? OR user_id=?)'}`,[id,id,...(admin?[]:[owner,u?.id||''])]);if(!order)throw new AppError('Order not found.',404);const [items,history,refunds,returns]=await Promise.all([all('SELECT * FROM order_items WHERE order_id=?',[order.id]),all('SELECT status,created_at FROM order_history WHERE order_id=? ORDER BY created_at',[order.id]),all('SELECT amount,method,reason,created_at FROM refunds WHERE order_id=?',[order.id]),all('SELECT * FROM returns WHERE order_id=?',[order.id])]);if(!admin){delete order.internal_notes;delete order.request_key;delete order.owner;}return {...order,items,history,refunds,returns};}
const transitions:Record<string,string[]>={New:['Confirmed','Cancelled'],Confirmed:['Processing','Cancelled'],Processing:['Packed','Cancelled'],Packed:['Shipped','Cancelled'],Shipped:['Out for Delivery','Returned'], 'Out for Delivery':['Delivered','Returned'],Delivered:['Returned'],Returned:[],Cancelled:[],Refunded:[]};
export async function changeOrder(id:string,data:Row,actor:Row){const old=await orderDetail(id,true);const patch:Row={updated_at:now()};if(data.payment_status==='Unpaid'&&old.payment_status!=='Unpaid')throw new AppError('A recorded payment cannot be marked unpaid; record a refund instead.');if(data.payment_status==='Paid'&&['Refunded','Partially refunded'].includes(old.payment_status))throw new AppError('Refunded payment totals must be preserved.');for(const k of ['internal_notes','courier','tracking','tracking_url'])if(typeof data[k]==='string')patch[k]=data[k].slice(0,1000);const ops:SqlStatement[]=[];if(data.status&&data.status!==old.status){if(!transitions[old.status]?.includes(data.status))throw new AppError(`Cannot move an order from ${old.status} to ${data.status}.`);ops.push(guard('SELECT status=? FROM orders WHERE id=?',[old.status,id]));patch.status=data.status;if(data.status==='Cancelled'){for(const item of old.items){ops.push(statement('INSERT INTO inventory_log (id,variant_id,previous,adjustment,quantity,reason,actor,created_at) SELECT ?,id,stock,?,stock+?,?,?,? FROM variants WHERE id=?',[uid(),item.quantity,item.quantity,'Cancellation '+old.number,actor.id,now(),item.variant_id]));ops.push(statement('UPDATE variants SET stock=stock+? WHERE id=?',[item.quantity,item.variant_id]));}}ops.push(insert('order_history',{id:uid(),order_id:id,status:data.status,actor:actor.id,created_at:now()}));ops.push(insert('outbox',{id:uid(),recipient:old.email,subject:`${old.number} · ${data.status}`,body:`Hello ${old.name},\n\nYour ${old.demo?'sample ':''}order ${old.number} is now ${data.status.toLowerCase()}.\n\nPaw & Co.`,status:old.demo?'sample':'pending',created_at:now()}));}if(data.payment_status){if(!['Unpaid','Paid'].includes(data.payment_status))throw new AppError('Refund status is calculated from recorded refunds.');patch.payment_status=data.payment_status;}
 ops.push(update('orders',patch,id),auditRecord(actor.id,'order updated',id,old,patch),clearGuards());await db().batch(ops);return orderDetail(id,true);}
