import { db, insert, one, now } from './db';
import { slugify } from './types';
export const defaults:Record<string,any>={store_name:'Paw & Co.',announcement:'Thoughtfully chosen essentials, for every kind of pet.',hero_title:'Their everyday.\nMade better.',hero_text:'Good food, favourite toys and the little things that make life with pets a little lovelier.',hero_image:'/images/hero.webp',contact_email:'',phone:'',whatsapp:'',address:'',hours:'',demo_mode:true,flat_shipping:250,free_shipping:5000,city_rates:{Lahore:200,Karachi:250,Islamabad:250},province_rates:{},weight_rate:0,pickup:false,pickup_address:'',cod_enabled:true,cod_max:25000,cod_blocked_cities:[],bank_enabled:false,bank_instructions:'',dispatch:'Dispatch details will be confirmed after order review.',returns_text:'Return eligibility and time limits must be set by the store owner before live trading.',ga_id:'',meta_pixel_id:'',social:{},sections:[{key:'featured',title:'Everyday favourites',enabled:true,pet:'',limit:4},{key:'new',title:'A little something new',enabled:true,pet:'',limit:4}],menu:[{label:'Dogs',href:'/dogs'},{label:'Cats',href:'/cats'},{label:'Birds',href:'/birds'},{label:'Fish',href:'/fish'},{label:'Small pets',href:'/small-pets'},{label:'All essentials',href:'/shop'},{label:'Pet care',href:'/pet-care'}]};
const items=[
 ['Adult dog food · Chicken','dogs','food',3299,24,'2 kg','sample:0','A chicken recipe for your dog’s everyday routine.'],
 ['Adult cat food · Chicken','cats','food',2499,20,'1 kg','sample:1','An everyday mealtime essential for adult cats.'],
 ['Salmon bites cat treats','cats','treats',649,36,'70 g','sample:2','Little rewards for your favourite companion.'],
 ['Natural clay cat litter','cats','litter-hygiene',1899,18,'10 L','sample:3','A practical staple for the daily litter-tray routine.'],
 ['Everyday ceramic bowl','dogs','feeding',1299,14,'600 ml','sample:4','A reassuringly weighty bowl in our signature forest green.'],
 ['Twist & tug rope toy','dogs','toys',799,22,'Medium','sample:5','A textured cotton rope toy for supervised playtime.'],
 ['The Sunday snooze bed','dogs','beds',5499,8,'Medium','sample:6','A soft, warm place to settle in after a busy day.'],
 ['Everyday walking harness','dogs','travel',2199,12,'Medium','sample:7','A forest-green harness for everyday walks together.'],
 ['Everyday bird seed mix','birds','food',899,16,'1 kg','sample:8','A sample bird food listing. Choose food suitable for your bird’s species.'],
 ['Aquarium fish flakes','fish','food',549,10,'100 g','sample:9','A sample aquarium food listing. Check suitability for your fish species.'],
 ['Meadow hay for rabbits','small-pets','food',1099,15,'1 kg','sample:10','A bag of meadow hay for a rabbit’s daily routine.'],
 ['Gentle everyday brush','cats','grooming',899,4,'One size','sample:11','A comfortable wooden brush for calm grooming moments.']
] as const;
export async function ensureSeed(){
 if(await one("SELECT key FROM settings WHERE key='seed_version'"))return;
 const date=now();const statements:any[]=[];
 for(const [key,value] of Object.entries(defaults))statements.push(insert('settings',{key,value:JSON.stringify(value)},true));
 for(const [i,name] of ['Dogs','Cats','Birds','Fish','Small pets','Food','Treats','Toys','Grooming','Beds','Feeding','Litter hygiene','Travel'].entries())statements.push(insert('categories',{id:slugify(name),kind:i<5?'pet':'department',name,slug:slugify(name),description:`Essentials for ${name.toLowerCase()}.`,sort_order:i,active:1},true));
 statements.push(insert('brands',{id:'paw-co',name:'Paw & Co. · Sample collection',slug:'paw-co',description:'Illustrative development collection. Product images, descriptions, prices and inventory are sample data.',featured:1,active:1},true));
 for(const [i,item] of items.entries()){
 const [name,pet,category,price,stock,label,image,description]=item;const id='sample-'+(i+1);
 statements.push(insert('products',{id,name,slug:slugify(name),brand_id:'paw-co',category_id:category,pet,description,details:'Development sample — this is not a verified product for sale. Replace the image, specifications, ingredients, instructions and pricing with approved supplier information before publishing for customers.',attributes:JSON.stringify({life_stage:'Adult',...(i<2?{flavour:'Chicken'}:{}),...(i===2?{flavour:'Salmon'}:{})}),image,featured:i<4?1:0,status:'published',demo:1,created_at:date,updated_at:date},true));
 statements.push(insert('variants',{id:id+'-v1',product_id:id,label,sku:'DEMO-'+String(i+1).padStart(3,'0')+'-A',price,stock,weight:i<2?2000:500},true));
 if(i===0||i===1||i===6||i===7)statements.push(insert('variants',{id:id+'-v2',product_id:id,label:i<2?'4 kg':'Large',sku:'DEMO-'+String(i+1).padStart(3,'0')+'-B',price:Math.round(price*(i<2?1.8:1.25)),stock:6,weight:4000},true));
 }
 const pages=[['about','About Paw & Co.','A considered collection for life with pets.','Paw & Co. is a working concept for a Pakistan-focused pet supplies store.\n\nThis private store contains clearly labelled sample products so you can explore shopping and management. No sample order will be fulfilled.'],['delivery','Delivery information','Know the cost before you order.','Delivery is calculated from the city, province, parcel weight and basket value using the store’s configured rates.\n\nThe checkout always shows delivery charges before the order is placed. The initial rates are sample settings. Actual courier coverage and dispatch times must be confirmed by the owner.'],['returns','Returns & refunds','Help with an order.','The store’s final return window, eligibility and refund terms have not yet been configured.\n\nYou can submit a return request from an order in your account. The store owner reviews requests before approving a return.'],['privacy','Privacy','Your information and choices.','This private sample store saves cart contents, account details and orders to support shopping. Newsletter consent is optional. No advertising trackers run unless configured and accepted.\n\nUse the contact form with “Privacy request” to request access or deletion. The owner must finalize the privacy policy, retention periods and business contact information before public launch.'],['terms','Terms & conditions','Sample store terms.','This is a private development store. Products, images, prices and delivery settings are illustrative. Sample orders do not create a purchase or promise of delivery.\n\nThe owner must replace this page with approved business terms before enabling live orders.'],['faq','Frequently asked questions','A few helpful answers.','How do I pay?\nCash on Delivery is available when enabled and the order meets the store’s configured limits. Other methods appear only when available.\n\nDo I need an account?\nNo. You can check out as a guest. Your order remains accessible in this browser.\n\nCan I use my own city?\nYes. Type your city in the delivery form.\n\nHow do I request a return?\nOpen your order and select Request a return.']];
 for(const [slug,title,summary,body] of pages)statements.push(insert('content',{id:slug,type:slug==='faq'?'faq':'page',slug,title,summary,body,status:'published',created_at:date,updated_at:date},true));
 const guides=[['a-bowl-for-everyday','A bowl for the everyday','A practical guide to choosing a pet bowl.','Consider your pet’s size, how easy the bowl is to clean, and whether it stays in place.\n\nCheck for a smooth finish and accessible edges. Wash food bowls after use and keep water bowls clean. Inspect bowls regularly and replace chipped or damaged ones.','sample:4'],['making-time-for-play','A little more time for play','Simple ideas for time spent together.','Choose toys that suit your pet’s size and play style. Check for loose pieces before each use.\n\nKeep play sessions supervised, rotate toys to maintain interest, and put damaged toys aside. Follow manufacturer guidance and ask your vet if you are unsure about a particular toy.','sample:5'],['a-comfortable-corner','Their own comfortable corner','Small details that make a restful space.','Choose a quiet place away from draughts and busy walkways. Leave enough space for your pet to turn around and settle naturally.\n\nLook for washable materials and check the manufacturer’s care instructions. Give your pet the choice of where to rest.','sample:6']];
 for(const [slug,title,summary,body,image] of guides)statements.push(insert('content',{id:slug,type:'article',slug,title,summary,body,image,status:'published',category:'Everyday care',created_at:date,updated_at:date},true));
 statements.push(insert('settings',{key:'seed_version',value:'1'},true));
 await db().batch(statements);
}
