import { z } from 'zod';
export const safeText = z.string().trim().max(10000);
export const phone = z.string().transform(s=>s.replace(/[\s()-]/g,'').replace(/^\+92/,'0').replace(/^0092/,'0')).refine(s=>/^03\d{9}$/.test(s),'Please enter a valid Pakistani mobile number, such as 0300 1234567.');
export const accountInput = z.object({name:z.string().trim().min(2).max(120),email:z.string().trim().email().max(200).transform(s=>s.toLowerCase()),password:z.string().min(12,'Use at least 12 characters.').max(128),phone:phone.optional()});
export const checkoutInput=z.object({name:z.string().trim().min(2,'Enter your full name.').max(120),email:z.string().trim().email('Enter a valid email address.').max(200).transform(s=>s.toLowerCase()),phone,address:z.string().trim().min(8,'Enter your complete street address.').max(500),city:z.string().trim().min(2,'Enter your delivery city.').max(100),province:z.string().trim().min(2).max(100),postal_code:z.string().trim().max(10).optional(),notes:z.string().max(1000).default(''),payment_method:z.enum(['cod','bank']),delivery_method:z.enum(['delivery','pickup']).default('delivery'),coupon:z.string().trim().max(50).default(''),request_key:z.string().uuid(),accept:z.literal(true),quote_token:z.string().min(1)});
export const cartInput=z.object({variant_id:z.string().min(1).max(100),quantity:z.number().int().min(0).max(99),mode:z.enum(['set','add']).default('add')});
export const variantInput=z.object({id:z.string().optional(),label:z.string().min(1).max(100),sku:z.string().min(1).max(100),price:z.number().int().min(0).max(10000000),sale_price:z.number().int().min(0).nullable().default(null),cost:z.number().int().min(0).default(0),stock:z.number().int().min(0).default(0),low_stock:z.number().int().min(0).default(5),weight:z.number().int().min(0).default(0),barcode:z.string().max(100).default(''),image:z.string().max(2000).default(''),backorder:z.number().int().min(0).max(1).default(0)}).refine(v=>v.sale_price===null||v.sale_price<v.price,{message:'Sale price must be below regular price.'});
export const productInput=z.object({name:z.string().trim().min(2).max(200),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),brand_id:z.string().min(1),category_id:z.string().min(1),pet:z.string().min(1).max(100),description:z.string().max(1000).default(''),details:safeText.default(''),attributes:z.string().max(10000).refine(s=>{try{const v=JSON.parse(s);return !!v&&!Array.isArray(v)&&typeof v==='object'&&Object.values(v).every(x=>['string','number','boolean'].includes(typeof x));}catch{return false;}},'Attributes must be a JSON object containing text, numbers or booleans.').default('{}'),image:z.string().max(2000).default(''),gallery:z.string().max(20000).refine(s=>{try{const v=JSON.parse(s);return Array.isArray(v)&&v.length<=20&&v.every(x=>typeof x==='string');}catch{return false;}},'Gallery must be a JSON array of up to 20 image URLs.').default('[]'),video:z.string().max(2000).default(''),featured:z.number().int().min(0).max(1).default(0),status:z.enum(['draft','published','archived']).default('draft'),publish_at:z.string().default(''),seo_title:z.string().max(200).default(''),seo_description:z.string().max(500).default(''),cod_disabled:z.number().int().min(0).max(1).default(0),demo:z.number().int().min(0).max(1).default(0),variants:z.array(variantInput).min(1).max(30)});
export class AppError extends Error { constructor(message:string,public status=400){super(message);} }
export function safeUrl(value:string,external=false){if(value===''||/^sample:\d+$/.test(value)||(/^\/(?!\/)/.test(value)&&!value.includes('\\')))return value;if(external){try{const u=new URL(value);if(u.protocol==='https:')return value;}catch{}}throw new AppError('Use a relative site path or an HTTPS image URL.');}
