export type FieldDef={key:string;label:string;type?:'text'|'number'|'textarea'|'toggle'|'select'|'image'|'datetime'|'password'|'rich';options?:string[];required?:boolean;help?:string};
export type ResourceDef={title:string;singular:string;description:string;columns:string[];fields:FieldDef[];create?:boolean};
const f=(key:string,label:string,type:FieldDef['type']='text',extra:Partial<FieldDef>={}):FieldDef=>({key,label,type,...extra});
export const configs:Record<string,ResourceDef>={
 products:{title:'Products',singular:'Product',description:'Manage the things on your shelves.',columns:['name','sku','category','price','stock','status'],fields:[],create:true},
 orders:{title:'Orders',singular:'Order',description:'From the first click to their front door.',columns:['number','name','city','created_at','payment_method','status','total'],fields:[]},
 inventory:{title:'Inventory',singular:'Stock adjustment',description:'Know what is available, and what needs attention.',columns:['name','label','sku','stock','low_stock','price'],fields:[]},
 categories:{title:'Categories',singular:'Category',description:'Keep the collection easy to explore.',columns:['name','kind','slug','parent_id','sort_order','active'],create:true,fields:[f('name','Name','text',{required:true}),f('slug','URL slug','text',{required:true}),f('kind','Category type','select',{options:['department','pet'],help:'Pet types appear automatically in the shop navigation and product editor.'}),f('parent_id','Parent category ID'),f('description','Description','textarea'),f('image','Category image','image'),f('sort_order','Display order','number'),f('active','Enabled','toggle'),f('seo_title','SEO title'),f('seo_description','Meta description','textarea'),f('attributes','Available attributes (JSON)','textarea',{help:'Example: ["life_stage", "flavour", "colour"]'})]},
 brands:{title:'Brands',singular:'Brand',description:'The names behind your collection.',columns:['name','slug','featured','active'],create:true,fields:[f('name','Brand name','text',{required:true}),f('slug','URL slug','text',{required:true}),f('description','Description','textarea'),f('image','Brand logo','image'),f('website','Website URL'),f('featured','Featured on homepage','toggle'),f('active','Enabled','toggle')]},
 customers:{title:'Customers',singular:'Customer',description:'Order history and practical customer notes.',columns:['name','email','phone','order_count','total_spend','blocked'],fields:[f('notes','Internal notes','textarea'),f('blocked','Block account and new orders','toggle')]},
 reviews:{title:'Reviews',singular:'Review',description:'Only delivered, verified purchases can leave a review.',columns:['product','customer','rating','content','status','created_at'],fields:[f('status','Moderation status','select',{options:['pending','approved','hidden','flagged']})]},
 discounts:{title:'Discounts',singular:'Discount',description:'Create offers with clear conditions and use limits.',columns:['code','type','value','minimum','uses','active'],create:true,fields:[f('code','Discount code','text',{required:true}),f('type','Discount type','select',{options:['percentage','fixed','free_shipping']}),f('value','Amount / percentage','number'),f('minimum','Minimum basket (PKR)','number'),f('max_uses','Maximum uses (0 = unlimited)','number'),f('per_customer','Uses per customer (0 = unlimited)','number'),f('starts','Starts (Pakistan time)','datetime'),f('expires','Expires (Pakistan time)','datetime'),f('category_id','Restrict to category ID'),f('product_id','Restrict to product ID'),f('customer_email','Restrict to customer email'),f('automatic','Apply automatically when eligible','toggle'),f('active','Enabled','toggle')]},
 content:{title:'Content',singular:'Page or article',description:'Helpful pages and stories, written in your voice.',columns:['title','type','slug','status','updated_at'],create:true,fields:[f('title','Title','text',{required:true}),f('slug','URL slug','text',{required:true}),f('type','Content type','select',{options:['page','article','faq']}),f('summary','Short introduction','textarea'),f('body','Content','rich'),f('image','Cover image','image'),f('author','Author'),f('category','Article category'),f('status','Publication status','select',{options:['draft','published','archived']}),f('publish_at','Publish after (Pakistan time)','datetime'),f('seo_title','SEO title'),f('seo_description','Meta description','textarea')]},
 banners:{title:'Banners',singular:'Banner',description:'Manage scheduled homepage campaigns.',columns:['title','button','href','active','sort_order'],create:true,fields:[f('title','Heading','text',{required:true}),f('text','Supporting text','textarea'),f('button','Button label'),f('href','Destination path'),f('image','Desktop image','image'),f('mobile_image','Mobile image','image'),f('starts','Starts (Pakistan time)','datetime'),f('expires','Expires (Pakistan time)','datetime'),f('active','Enabled','toggle'),f('sort_order','Display order','number')]},
 users:{title:'Team & permissions',singular:'Team member',description:'Access is checked on the server for every action.',columns:['name','email','role','blocked','created_at'],create:true,fields:[f('name','Full name','text',{required:true}),f('email','Email address','text',{required:true}),f('role','Role','select',{options:['super_admin','manager','order_manager','inventory_manager','content_editor']}),f('password','Password','password',{help:'At least 12 characters. Leave blank to keep an existing password.'}),f('blocked','Disable access','toggle')]},
 messages:{title:'Customer messages',singular:'Message',description:'Enquiries and privacy requests in one place.',columns:['name','email','subject','status','created_at'],fields:[f('status','Status','select',{options:['New','In progress','Resolved']})]},
 returns:{title:'Returns',singular:'Return request',description:'Review the request before approving a return.',columns:['order_id','reason','items','status','created_at'],fields:[f('status','Return status','select',{options:['Requested','Approved','Rejected','Received','Refunded']})]},
 refunds:{title:'Refunds',singular:'Refund',description:'Record completed refunds. No money is moved by this form.',columns:['order_id','amount','method','reason','created_at'],fields:[],create:false},
 newsletter:{title:'Newsletter',singular:'Subscriber',description:'People who explicitly opted in to updates.',columns:['email','name','created_at'],fields:[]},
 audit:{title:'Activity log',singular:'Activity',description:'A record of important administrative changes.',columns:['actor','action','resource','created_at'],fields:[]},
 outbox:{title:'Email queue',singular:'Email',description:'Order messages are queued independently of checkout. Sample messages are never sent.',columns:['recipient','subject','status','attempts','created_at'],fields:[]}
};
export const friendly=(key:string)=>({created_at:'Created',updated_at:'Updated',low_stock:'Alert below',payment_method:'Payment',total_spend:'Total spend',order_count:'Orders',parent_id:'Parent',sort_order:'Order',order_id:'Order',active:'Enabled',blocked:'Blocked'} as Record<string,string>)[key]||key.replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
export function exportCSV(rows:Record<string,any>[],name:string){if(!rows.length)return;const keys=Object.keys(rows[0]);const escape=(v:any)=>{let s=typeof v==='object'?JSON.stringify(v):String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const csv=[keys.map(escape).join(','),...rows.map(r=>keys.map(k=>escape(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw new Error('CSV contains an unfinished quoted field.');if(cell||row.length){row.push(cell);rows.push(row);}const headers=rows.shift()?.map(s=>s.replace(/^\uFEFF/,'').trim())||[];return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])));}

export function productImports(values:Record<string,string>[],existing:Record<string,any>[]) {
 const groups=new Map<string,{id?:string;data:Record<string,any>}>();
 for(const row of values){
  if(!row.name||!row.sku||!row.brand_id||!row.category_id)throw new Error('CSV requires name, sku, brand_id and category_id.');
  const slug=row.slug||row.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  let group=groups.get(slug);
  if(!group){const old=existing.find(p=>p.slug===slug);group={id:old?.id,data:{...old,...row,slug,pet:row.pet||old?.pet||'dogs',status:row.status||old?.status||'draft',variants:old?old.variants.map((v:any)=>({...v})):[]}};for(const key of ['demo','featured','cod_disabled'])group.data[key]=Number(row[key]??old?.[key]??0);groups.set(slug,group);}
  const old=group.data.variants.find((v:any)=>v.sku===row.sku);
  const variant:Record<string,any>={...old,label:row.label||old?.label||'Default',sku:row.sku};
  for(const key of ['price','stock','cost','low_stock','weight','backorder'])if(row[key]!==undefined)variant[key]=Number(row[key]);
  if(row.sale_price!==undefined)variant.sale_price=row.sale_price===''?null:Number(row.sale_price);
  for(const key of ['barcode','image'])if(row['variant_'+key]!==undefined)variant[key]=row['variant_'+key];
  if(old)Object.assign(old,variant);else group.data.variants.push(variant);
 }
 return [...groups.values()];
}
