'use client';
import { useState } from 'react';
import { ArrowRight,ArrowUpRight,Mail,Phone,MapPin } from 'lucide-react';
import { Accordion,AccordionItem,AccordionTrigger,AccordionContent } from '@/components/ui/accordion';
import { toast } from 'sonner';
import { useStore,api } from './context';
import { Breadcrumb,SafeText,Field,ProductImage,Blank } from './shared';
export function ContentPage({route}:{route:string[]}){const {data}=useStore();const [busy,setBusy]=useState(false),[sent,setSent]=useState(false);if(route[0]==='contact')return <main id="main" className="container content-page"><Breadcrumb items={[{label:'Contact'}]}/><div className="page-intro"><p className="eyebrow">HERE FOR YOU & YOUR PET</p><h1>A little help goes a long way.</h1><p>Ask about a product, an order or anything in between.</p></div><div className="contact-layout"><div><h2>Let’s talk.</h2>{data.settings.contact_email&&<p><Mail size={20}/><a href={'mailto:'+data.settings.contact_email}>{data.settings.contact_email}</a></p>}{data.settings.phone&&<p><Phone size={20}/>{data.settings.phone}</p>}{data.settings.address&&<p><MapPin size={20}/>{data.settings.address}</p>}{data.settings.hours&&<p>{data.settings.hours}</p>}<p className="muted">Messages sent here are saved for the store team. Please include your order number if you have one.</p><a className="text-link" href="/faq">You may find your answer in our FAQs <ArrowUpRight size={17}/></a></div>{sent?<div className="notice"><h2>Thanks for getting in touch.</h2><p>Your message is saved for the store team.</p><button className="text-button" onClick={()=>setSent(false)}>Send another message</button></div>:<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('contact',Object.fromEntries(new FormData(e.currentTarget)));setSent(true);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}><Field label="Your name"><input name="name" required minLength={2}/></Field><Field label="Email address"><input name="email" type="email" required/></Field><Field label="Subject"><input name="subject" required minLength={2}/></Field><Field label="How can we help?"><textarea name="message" rows={5} minLength={10} required/></Field><input name="website" tabIndex={-1} autoComplete="off" className="honeypot" aria-hidden="true"/><button disabled={busy} className="btn">{busy?'Sending…':'Send message'}<ArrowRight size={18}/></button></form>}</div></main>;
 if(route[0]==='pet-care'&&!route[1])return <main id="main" className="container care-page"><Breadcrumb items={[{label:'Pet-care journal'}]}/><div className="page-intro"><p className="eyebrow">THE PET-CARE JOURNAL</p><h1>A little know-how.<br/>A lot of care.</h1><p>Practical ideas for the everyday moments you share.</p></div><div className="care-grid">{data.pages.filter(p=>p.type==='article').map(p=><a key={p.id} href={'/pet-care/'+p.slug}><ProductImage image={p.image} alt={p.title}/><p className="eyebrow">{p.category}</p><h2>{p.title}</h2><p>{p.summary}</p></a>)}</div></main>;
 const page=data.pages.find(p=>p.slug===(route[1]||route[0]));if(!page)return <main className="container"><Blank title="This page wandered off." text="Let’s get you back to the good stuff." action="Back to the shop"/></main>;return <main id="main" className="container content-page"><Breadcrumb items={[...(page.type==='article'?[{label:'Pet care',href:'/pet-care'}]:[]),{label:page.title}]}/><article className="article"><p className="eyebrow">{page.type==='article'?page.category:'PAW & CO.'}</p><h1>{page.title}</h1><p className="article-summary">{page.summary}</p>{page.image&&<ProductImage image={page.image} alt={page.title}/>} {page.type==='article'&&<p className="muted">By {page.author} · {new Date(page.created_at).toLocaleDateString('en-PK',{timeZone:'Asia/Karachi'})}</p>}{page.type==='faq'?<Accordion type="multiple">{String(page.body).split('\n\n').map((p,i)=>{const [title,...text]=p.split('\n');return <AccordionItem value={String(i)} key={i}><AccordionTrigger>{title}</AccordionTrigger><AccordionContent>{text.join('\n')}</AccordionContent></AccordionItem>;})}</Accordion>:<SafeText text={page.body}/>}</article></main>;}
