'use client';
import { createContext,useContext,useState,useEffect,useCallback,type ReactNode } from 'react';
import { toast } from 'sonner';
import { Toaster } from '@/components/ui/sonner';
import type { Catalog,Cart,Row } from '@/lib/types';
export async function api(path:string,data?:unknown,method?:string):Promise<any>{const r=await fetch('/api/'+path,{method:method||(data===undefined?'GET':'POST'),headers:data===undefined?undefined:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const json:any=await r.json();if(!r.ok)throw new Error(json.error||'Something went wrong.');return json;}
type StoreContext={data:Catalog;cart:Cart;loading:boolean;cartOpen:boolean;setCartOpen:(v:boolean)=>void;refresh:()=>Promise<void>;add:(id:string,quantity?:number)=>Promise<void>;quantity:(id:string,n:number)=>Promise<void>;wish:(id:string)=>Promise<void>};
const Context=createContext<StoreContext|null>(null);
export function useStore(){const c=useContext(Context);if(!c)throw new Error('Missing storefront context');return c;}
export function StoreProvider({data,children}:{data:Catalog;children:ReactNode}){const [cart,setCart]=useState<Cart>({items:[],wishlist:[],subtotal:0,user:null});const [loading,setLoading]=useState(true);const [cartOpen,setCartOpen]=useState(false);const refresh=useCallback(async()=>{try{setCart(await api('cart'));}catch(e){toast.error((e as Error).message);}finally{setLoading(false);}},[]);useEffect(()=>{void refresh();},[refresh]);const add=async(id:string,n=1)=>{try{setCart(await api('cart',{variant_id:id,quantity:n,mode:'add'}));toast.success('Added to your basket.');setCartOpen(true);}catch(e){toast.error((e as Error).message);throw e;}};const quantity=async(id:string,n:number)=>{try{setCart(await api('cart',{variant_id:id,quantity:n,mode:'set'}));}catch(e){toast.error((e as Error).message);}};const wish=async(id:string)=>{try{setCart(await api('wishlist',{product_id:id,saved:!cart.wishlist.includes(id)}));}catch(e){toast.error((e as Error).message);}};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();const register=(t:any)=>Promise.resolve(ctx.registerTool(t,{signal:controller.signal})).catch(()=>{});void register({name:'search_pet_products',description:'Find current catalog products by keyword or pet type.',inputSchema:{type:'object',properties:{query:{type:'string'},pet:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(v:Row)=>{if(v.query!==undefined&&typeof v.query!=='string')throw new Error('query must be a string');if(v.pet!==undefined&&typeof v.pet!=='string')throw new Error('pet must be a string');return data.products.filter(p=>(!v.pet||p.pet===v.pet)&&(!v.query||(p.name+' '+p.brand+' '+p.category).toLowerCase().includes(v.query.toLowerCase()))).map(p=>({id:p.id,name:p.name,slug:p.slug,variants:p.variants.map(v=>({id:v.id,label:v.label,price:v.sale_price??v.price,stock:v.stock}))}));}});void register({name:'add_pet_product_to_basket',description:'Add one current product variant to the basket and open the visible basket. Does not place an order.',inputSchema:{type:'object',properties:{variant_id:{type:'string'},quantity:{type:'integer',minimum:1,maximum:99}},required:['variant_id','quantity'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(v:Row)=>{if(typeof v.variant_id!=='string'||!Number.isInteger(v.quantity)||v.quantity<1||v.quantity>99)throw new Error('A valid variant and quantity from 1 to 99 are required.');const c=await api('cart',{variant_id:v.variant_id,quantity:v.quantity,mode:'add'});setCart(c);setCartOpen(true);return {items:c.items.map((i:Row)=>({variant_id:i.variant_id,quantity:i.quantity})),subtotal:c.subtotal};}});return()=>controller.abort();},[data]);
 return <Context.Provider value={{data,cart,loading,cartOpen,setCartOpen,refresh,add,quantity,wish}}>{children}<Toaster richColors theme="light" position="bottom-center"/></Context.Provider>;
}
