'use client';
import { useMemo,useState } from 'react';
import { SlidersHorizontal,X } from 'lucide-react';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetTrigger,SheetClose } from '@/components/ui/sheet';
import { Checkbox } from '@/components/ui/checkbox';
import { Slider } from '@/components/ui/slider';
import { Pagination,PaginationContent,PaginationItem,PaginationLink } from '@/components/ui/pagination';
import { useStore } from './context';
import { Blank,Breadcrumb,ProductGrid,Choice } from './shared';
import { price,money } from '@/lib/types';
export function Listing({route,query}:{route:string[];query:Record<string,string>}){const {data}=useStore();const brandRoute=route[0]==='brands'?data.brands.find(b=>b.slug===route[1]):null;const petRoute=data.categories.find(c=>c.kind==='pet'&&c.slug===route[0]);const [pet,setPet]=useState(petRoute?.id||query.pet||'');const [category,setCategory]=useState(query.category||'');const [brand,setBrand]=useState(brandRoute?.id||'');const [sort,setSort]=useState(query.sort||'featured');const [stock,setStock]=useState(false);const [sale,setSale]=useState(route[0]==='offers');const priceCeiling=Math.max(20000,...data.products.flatMap(p=>p.variants.map(v=>Math.ceil(price(v)/250)*250)));const [max,setMax]=useState(priceCeiling);const [life,setLife]=useState('');const [flavour,setFlavour]=useState('');const [page,setPage]=useState(1);const term=query.q||'';const attrs=data.products.map(p=>{try{return JSON.parse(p.attributes);}catch{return {};}});const lives=[...new Set(attrs.map(a=>a.life_stage).filter(Boolean))] as string[];const flavours=[...new Set(attrs.map(a=>a.flavour).filter(Boolean))] as string[];
 const result=useMemo(()=>{let r=data.products.filter(p=>{const v=p.variants[0];if(!v)return false;const words=term.toLowerCase().split(/\s+/).filter(Boolean);const hay=(p.name+' '+p.brand+' '+p.pet+' '+p.category+' '+p.variants.map(v=>v.sku).join(' ')).toLowerCase();let attr:any={};try{attr=JSON.parse(p.attributes);}catch{}return (!pet||p.pet===pet)&&(!category||p.category_id===category)&&(!brand||p.brand_id===brand)&&words.every(w=>hay.includes(w))&&price(v)<=max&&(!stock||p.variants.some(v=>v.stock>0||v.backorder))&&(!sale||p.variants.some(v=>price(v)<v.price))&&(!life||attr.life_stage===life)&&(!flavour||attr.flavour===flavour);});if(sort==='price-low')r.sort((a,b)=>price(a.variants[0])-price(b.variants[0]));else if(sort==='price-high')r.sort((a,b)=>price(b.variants[0])-price(a.variants[0]));else if(sort==='newest')r.sort((a,b)=>b.created_at.localeCompare(a.created_at));else if(sort==='rating')r.sort((a,b)=>b.rating-a.rating);else if(sort==='best-selling')r.sort((a,b)=>b.sold-a.sold);else r.sort((a,b)=>b.featured-a.featured);return r;},[data,pet,category,brand,sort,stock,sale,max,term,life,flavour]);
 const clear=()=>{setPet('');setCategory('');setBrand('');setStock(false);setSale(false);setMax(priceCeiling);setLife('');setFlavour('');setPage(1);};const title=term?`Results for “${term}”`:route[0]==='offers'?'A little more for less.':brandRoute?brandRoute.name:petRoute?`Good things for ${petRoute.name.toLowerCase()}.`:'Thoughtfully chosen essentials.';
 const filters=<div className="filter-content"><div className="filter-heading"><strong>Filter by</strong><button className="text-button" onClick={clear}>Clear all</button></div><fieldset><legend>Pet type</legend>{data.categories.filter(c=>c.kind==='pet').map(c=><label key={c.id} className="checkbox-label"><Checkbox checked={pet===c.id} onCheckedChange={v=>{setPet(v===true?c.id:'');setPage(1);}}/><span>{c.name}</span><small>{data.products.filter(p=>p.pet===c.id).length}</small></label>)}</fieldset><fieldset><legend>Category</legend><Choice label="Product category" value={category} onChange={v=>{setCategory(v);setPage(1);}} options={[{value:'',label:'All categories'},...data.categories.filter(c=>c.kind!=='pet').map(c=>({value:c.id,label:c.name}))]}/></fieldset><fieldset><legend>Brand</legend><Choice label="Brand" value={brand} onChange={setBrand} options={[{value:'',label:'All brands'},...data.brands.map(b=>({value:b.id,label:b.name}))]}/></fieldset><fieldset><legend>Price range</legend><p className="price-range">Rs. 0 <span>{money(max)}</span></p><Slider min={0} max={priceCeiling} step={250} value={[max]} onValueChange={v=>{setMax(v[0]);setPage(1);}} aria-label="Maximum price"/></fieldset>{lives.length>0&&<fieldset><legend>Life stage</legend><Choice label="Life stage" value={life} onChange={setLife} options={[{value:'',label:'All life stages'},...lives]}/></fieldset>}{flavours.length>0&&<fieldset><legend>Flavour</legend><Choice label="Flavour" value={flavour} onChange={setFlavour} options={[{value:'',label:'All flavours'},...flavours]}/></fieldset>}<fieldset><legend>Availability</legend><label className="checkbox-label"><Checkbox checked={stock} onCheckedChange={v=>setStock(v===true)}/>In stock only</label><label className="checkbox-label"><Checkbox checked={sale} onCheckedChange={v=>setSale(v===true)}/>On sale</label></fieldset></div>;
 return <main id="main" className="container listing-page"><Breadcrumb items={[{label:brandRoute?'Brands':'Shop'}]}/><div className="page-intro"><p className="eyebrow">THE PAW & CO. COLLECTION</p><h1>{title}</h1><p>{brandRoute?.description||'Food, play and all the little things in between.'}</p></div><div className="listing-layout"><aside className="filter-sidebar">{filters}</aside><div className="listing-results"><div className="listing-toolbar"><span>{result.length} {result.length===1?'product':'products'}</span><Sheet><SheetTrigger className="mobile-filter btn outline"><SlidersHorizontal size={16}/> Filters</SheetTrigger><SheetContent side="left" className="filters-drawer"><SheetHeader><SheetTitle>Refine your search</SheetTitle><SheetDescription>Find the right essentials for your pet.</SheetDescription></SheetHeader>{filters}<SheetClose className="btn">Show {result.length} products</SheetClose></SheetContent></Sheet><Choice label="Sort products" value={sort} onChange={setSort} options={[{value:'featured',label:'Featured'},{value:'newest',label:'Newest'},{value:'best-selling',label:'Best selling'},{value:'price-low',label:'Price: low to high'},{value:'price-high',label:'Price: high to low'},{value:'rating',label:'Highest rated'}]}/></div>{(pet||category||sale)&&<div className="active-filters">{pet&&<button onClick={()=>setPet('')}>{pet}<X size={13}/></button>}{category&&<button onClick={()=>setCategory('')}>{data.categories.find(c=>c.id===category)?.name}<X size={13}/></button>}{sale&&<button onClick={()=>setSale(false)}>On sale<X size={13}/></button>}</div>}{result.length?<ProductGrid products={result.slice((Math.min(page,Math.ceil(result.length/12))-1)*12,Math.min(page,Math.ceil(result.length/12))*12)}/>:<Blank title={term?`We couldn’t find a match for “${term}”.`:'No products match these filters.'} text={sale?'There are no active sale prices in this collection. Browse all essentials or check back later.':'Try another spelling, a broader search or fewer filters.'} action="Browse all essentials"/>}{result.length>12&&<Pagination><PaginationContent>{Array.from({length:Math.ceil(result.length/12)},(_,i)=><PaginationItem key={i}><PaginationLink href="#" isActive={page===i+1} onClick={e=>{e.preventDefault();setPage(i+1);}}>{i+1}</PaginationLink></PaginationItem>)}</PaginationContent></Pagination>}</div></div></main>;}
