'use client';
import { useState,type ReactNode } from 'react';
import { Heart,Plus,Minus,ArrowUpRight,Package,Check,ChevronRight } from 'lucide-react';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { useStore } from './context';
import { price,money,type Product } from '@/lib/types';
export function ProductImage({image,alt,className=''}:{image:string;alt:string;className?:string}){if(image?.startsWith('sample:')){const i=Number(image.split(':')[1]);return <span role="img" aria-label={alt} className={'product-photo '+className} style={{backgroundImage:'url(/images/sample-products.webp)',backgroundSize:'400% 300%',backgroundPosition:`${(i%4)*100/3}% ${Math.floor(i/4)*50}%`}}/>;}return image?<img src={image} alt={alt} className={'product-photo '+className} loading="lazy"/>:<span className={'product-photo no-photo '+className}><Package aria-hidden/><span>Image to be added</span></span>;}
export function PetPhoto({pet}:{pet:string}){return <span role="img" aria-label={pet==='small-pets'?'A tan rabbit':pet} className={'pet-photo pet-'+pet}/>;}
export function Choice({value,onChange,options,label,className=''}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];label:string;className?:string}){return <Select value={value||'__all'} onValueChange={v=>onChange(v==='__all'?'':v)}><SelectTrigger aria-label={label} className={'choice '+className}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=>typeof o==='string'?<SelectItem key={o} value={o||'__all'}>{o||'All'}</SelectItem>:<SelectItem key={o.value} value={o.value||'__all'}>{o.label}</SelectItem>)}</SelectContent></Select>;}
export function Stepper({value,onChange,max=99}:{value:number;onChange:(n:number)=>void;max?:number}){return <div className="stepper"><button type="button" onClick={()=>onChange(Math.max(0,value-1))} aria-label="Decrease quantity"><Minus size={15}/></button><span aria-live="polite">{value}</span><button type="button" disabled={value>=max} onClick={()=>onChange(value+1)} aria-label="Increase quantity"><Plus size={15}/></button></div>;}
export function ProductCard({product:p}:{product:Product}){const s=useStore();const [busy,setBusy]=useState(false);const v=p.variants[0];if(!v)return null;return <article className="product-card"><div className="product-visual"><a href={'/products/'+p.slug} aria-label={p.name}><ProductImage image={p.image} alt={p.name}/></a>{price(v)<v.price&&<span className="sale-label">{Math.round((1-price(v)/v.price)*100)}% off</span>}<button className={'wish-button '+(s.cart.wishlist.includes(p.id)?'saved':'')} aria-label={(s.cart.wishlist.includes(p.id)?'Remove from':'Add to')+' wishlist: '+p.name} onClick={()=>s.wish(p.id)}><Heart size={19} fill={s.cart.wishlist.includes(p.id)?'currentColor':'none'}/></button></div><div className="product-copy"><p className="eyebrow">{p.brand.split(' · ')[0]} {p.demo?<span className="sample-label">Sample</span>:null}</p><a className="product-name" href={'/products/'+p.slug}>{p.name}</a><p className="product-meta">{v.label}{p.review_count>0?` · ★ ${p.rating.toFixed(1)} (${p.review_count})`:''}</p><div className="product-bottom"><div><strong>{money(price(v))}</strong>{price(v)<v.price&&<del>{money(v.price)}</del>}</div><button className="quick-add" disabled={busy||(!v.stock&&!v.backorder)} aria-label={'Add '+p.name+' to basket'} onClick={async()=>{setBusy(true);try{await s.add(v.id);}catch{}finally{setBusy(false);}}}>{busy?'…':<Plus size={20}/>}</button></div>{v.stock===0&&!v.backorder?<span className="stock-label">Out of stock</span>:v.stock>0&&v.stock<=v.low_stock?<span className="stock-label">Only {v.stock} left</span>:null}</div></article>;}
export function ProductGrid({products}:{products:Product[]}){return <div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>;}
export function SectionTitle({title,subtitle,href='/shop',link='View all'}:{title:string;subtitle?:string;href?:string;link?:string}){return <div className="section-title"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><a className="text-link" href={href}>{link}<ArrowUpRight size={18}/></a></div>;}
export function Blank({title,text,action,href='/shop'}:{title:string;text:string;action?:string;href?:string}){return <Empty className="blank-state"><EmptyHeader><Package size={36} strokeWidth={1.3}/><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{text}</EmptyDescription></EmptyHeader>{action&&<a className="btn" href={href}>{action}</a>}</Empty>;}
export function Breadcrumb({items}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a>{items.map((i,n)=><span key={n}><ChevronRight size={13}/>{i.href?<a href={i.href}>{i.label}</a>:i.label}</span>)}</nav>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function SafeText({text}:{text:string}){return <div className="rich-text">{text.split('\n\n').map((p,i)=>p.startsWith('## ')?<h2 key={i}>{p.slice(3)}</h2>:p.startsWith('# ')?<h2 key={i}>{p.slice(2)}</h2>:p.startsWith('- ')?<ul key={i}>{p.split('\n').map((s,n)=><li key={n}>{s.replace(/^- /,'')}</li>)}</ul>:<p key={i}>{p.split(/(\*\*.*?\*\*)/g).map((s,n)=>s.startsWith('**')?<strong key={n}>{s.slice(2,-2)}</strong>:s)}</p>)}</div>;}
